maxPlayers: 16
minPlayers: 8
gortumeTimer: 30
lobbyTime: 90
gameTimer: 600
batTimer: 30
enabled:

developers:
- avery246813579
- limebyte
owners:
- gizzy14gazza
- shazz96
- enayet123
mods:
- Queen_Cerii

