name: Gortume
main: com.eyeofender.gortume.HideAndGo
version: 1.3.6
authors: [avery246813579, LimeByte]
description: Gortume minigame for TheMass.
database: false
commands:
    set:
        description: Sets a Gortume waypoint to your location.
        usage: /<command> <waypoint> <arena>
        aliases: s
    create:
        description: Creates a arena with the specified name.
        usage: /<command> <arenaName>
    join:
        description: Joins the specified arena.
        usage: /<command> <arena>
        aliases: j
    countdown:
        description: Starts the arena countdown.
        usage: /<command>
    leave:
        description: Leaves the current arena.
        usage: /<command>
        aliases: l
    pass:
        description: Uses a Gortume pass.
        usage: /<command>
        aliases: p
    enable:
        description: Enables the specified arena.
        usage: /<command> <arena>
        aliases: e
    kit:
        description: Selects a kit.
        usage: /<command> <Travler|Ninja|Tank|Spy|God>
        aliases: k
    gortume:
        description: Gets the running version of Gortume.
        usage: /<command>
        aliases: g
