name: Gortume
main: com.eyeofender.gortume.HideAndGo
version: 1.01.1
author: avery246813579
description: Gortume A simple plugin.
database: true
commands:
  Set:
    description: Sets gortume points.
  S:
    description: Sets gortume points.  
  Create:
    description: Creates a arena.
  Join:
    description: Sets gortume points.   
  Countdown:
    description: Sets gortume points. 
  C:
    description: Sets gortume points. 
  Leave:
    description: Sets gortume points.                
  L:
    description: Sets gortume points.                
  Pass:
    description: Sets gortume points.  
  Enable:
    description: Discription.                                          
