name: Gortume
main: com.eyeofender.gortume.HideAndGo
version: 1.3.2
authors: [avery246813579, LimeByte]
description: Gortume A simple plugin.
database: false
commands:
    Set:
        description: Sets gortume points.
    S:
        description: Sets gortume points.
    Create:
        description: Creates a arena.
    Join:
        description: Sets gortume points.
    Countdown:
        description: Sets gortume points.
    C:
        description: Sets gortume points.
    Leave:
        description: Sets gortume points.
    L:
        description: Sets gortume points.
    Pass:
        description: Sets gortume points.
    Enable:
        description: Description.
    Kit:
        description: Description.
    version:
        description: Gets the running version of Gortume.
