name: Gortume
main: com.eyeofender.gortume.HideAndGo
version: 1.4.4
authors: [avery246813579, LimeByte]
description: Gortume minigame for TheMass.
database: true
commands:
    set:
        description: Sets a Gortume waypoint to your location.
        usage: /<command> <waypoint> <arena>
        aliases: s
        permission: gortume.command.set
    create:
        description: Creates a arena with the specified name.
        usage: /<command> <arenaName>
        permission: gortume.command.create
    join:
        description: Joins the specified arena.
        usage: /<command> <arena>
        aliases: j
        permission: gortume.command.join
    countdown:
        description: Starts the arena countdown.
        usage: /<command>
        permission: gortume.command.countdown
    leave:
        description: Leaves the current arena.
        usage: /<command>
        aliases: l
        permission: gortume.command.leave
    pass:
        description: Uses a Gortume pass.
        usage: /<command>
        aliases: p
        permission: gortume.command.pass
    enable:
        description: Enables the specified arena.
        usage: /<command> <arena>
        aliases: e
        permission: gortume.command.enable
    kit:
        description: Selects a kit.
        usage: /<command> <Travler|Ninja|Tank|Spy|God>
        aliases: k
        permission: gortume.command.kit
    gortume:
        description: Gets the running version of Gortume.
        usage: /<command>
        aliases: g
        permission: gortume.command.gortume
    givepass:
        description: Gives a player a pass.
        usage: /<command> <player>
        permission: gortume.command.givepass

permissions:
    gortume.user:
        description: Grants the player all user commands.
        default: true
        children:
            gortume.command.join: true
            gortume.command.leave: true
            gortume.command.pass: true
            gortume.command.kit: true
            gortume.command.gortume: true
    gortume.admin:
        description: Grants the player all admin commands.
        default: op
        children:
            gortume.user: true
            gortume.command.set: true
            gortume.command.create: true
            gortume.command.countdown: true
            gortume.command.enable: true
            gortume.command.givepass: true
    gortume.command.set:
        description: Allows the user to run the set command.
    gortume.command.create:
        description: Allows the user to run the create command.
    gortume.command.join:
        description: Allows the user to run the join command.
    gortume.command.leave:
        description: Allows the user to run the leave command.
    gortume.command.countdown:
        description: Allows the user to run the countdown command.
    gortume.command.leave:
        description: Allows the user to run the leave command.
    gortume.command.pass:
        description: Allows the user to run the pass command.
    gortume.command.enable:
        description: Allows the user to run the enable command.
    gortume.command.kit:
        description: Allows the user to run the kit command.
    gortume.command.gortume:
        description: Allows the user to run the gortume command.
    gortume.command.givepass:
        description: Allows the user to run the givepass command.